# PHP
# Test and package your PHP project.
# Add steps that run tests, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/php

trigger:
- master
variables:
- group: common
stages:
  - stage: 'Build'
    displayName: 'Build the web application'
    jobs:
      - job: 'Build'
        displayName: 'Build job'
        pool:
          vmImage: 'ubuntu-latest'
        variables:
          phpVersion: 7.2
        steps:
        - task: CopyFiles@2
          displayName: 'Copy Files to: $(Build.artifactstagingdirectory)'
          inputs:
            SourceFolder: '$(Build.sourcesdirectory)'
            Contents: |
              **/*.php
              **/*.css
            TargetFolder: '$(Build.artifactstagingdirectory)'
        - task: ArchiveFiles@2
          inputs:
            rootFolderOrFile: '$(Build.artifactstagingdirectory)/code'
            includeRootFolder: false
            archiveType: 'zip'
            archiveFile: '$(Build.ArtifactStagingDirectory)/code$(Build.BuildId).zip'
            replaceExistingArchive: true
        - task: ArchiveFiles@2
          inputs:
            rootFolderOrFile: '$(Build.SourcesDirectory)/ansible'
            includeRootFolder: false
            archiveType: 'zip'
            archiveFile: '$(Build.ArtifactStagingDirectory)/ansible$(Build.BuildId).zip'
            replaceExistingArchive: true
        - task: PublishBuildArtifacts@1
          inputs:
            PathtoPublish: '$(Build.ArtifactStagingDirectory)/code$(Build.BuildId).zip'
            ArtifactName: 'drop'
            publishLocation: 'Container'
        - task: PublishBuildArtifacts@1
          inputs:
            PathtoPublish: '$(Build.ArtifactStagingDirectory)/ansible$(Build.BuildId).zip'
            ArtifactName: 'drop'
            publishLocation: 'Container'
        - task: PublishBuildArtifacts@1
          inputs:
            PathtoPublish: '$(Build.sourcesdirectory)/sql/users.sql'
            ArtifactName: 'drop'
            publishLocation: 'Container'
  - stage: 'Dev'
    displayName: 'Deploy the web application to dev server'
    dependsOn: Build
    jobs:
    - template: deploy-stage-template.yml
      parameters:
        TargetEnvironment: 'dev'
  - stage: 'Preprod'
    displayName: 'Deploy the web application to preprod server'
    dependsOn: Dev
    jobs:
    - template: deploy-stage-template.yml
      parameters:
        TargetEnvironment: 'preprod'