jobs:
  - job: 'Deploy'
    displayName: 'Deploy job'
    pool:
      vmImage: 'vs2017-win2016'
    variables:
      webappName: 'gutimore-ansible-webapp'
      mysqlServerName: 'gutimore-ansible-mysql-server'
    steps:
    - task: qetza.replacetokens.replacetokens-task.replacetokens@3
      displayName: 'Replace variables in Ansible script to deploy Azure resources'
      inputs:
        targetFiles: 'ansible/*.yml'
        escapeType: none
        tokenPrefix: '__'
        tokenSuffix: '__'
    - task: Ansible@0
      inputs:
        ansibleInterface: 'remoteMachine'
        connectionOverSsh: 'AnsibleVMSSHConn'
        playbookSourceRemoteMachine: 'agentMachine'
        playbookRootRemoteMachine: '$(System.DefaultWorkingDirectory)/ansible'
        playbookPathLinkedArtifactOnRemoteMachine: 'playbook.yml'
        inventoriesRemoteMachine: 'hostList'
        inventoryHostListRemoteMachine: 'gutimore-ansible-controller.eastus.cloudapp.azure.com'
        failOnStdErr: false
    - download: current
      artifact: drop

    - task: AzureRmWebAppDeployment@4
      displayName: 'Azure App Service Deploy'
      inputs:
        ConnectionType: 'AzureRM'
        azureSubscription: 'AzureRmPipeline-conn'
        WebAppName: '$(webappName)'
        Package: '$(Pipeline.Workspace)/drop/**/*.zip'
        AppSettings: '$(WebAppServerConnString_dev)'
        TakeAppOfflineFlag: true
        UseWebDeploy: true
        RemoveAdditionalFilesFlag: true