---


- hosts: localhost


  vars:
    resource_group: __resourceGroupName__
    location: __location__
    webapp_name: __webappName__
    mysqlserver_name: __mysqlServerName__
    mysqldb_name: __mysqlDbName__
    admin_username: __mysqlUsername__
    admin_password: __mysqlPassword__
    asp_name: __aspName__
    connection_string: __WebAppServerConnString__

  tasks:
    - name: Create a resource group
      azure_rm_resourcegroup:
        name: "{{ resource_group }}"
        location: "{{ location }}"

    - name: Create App Service on Linux with php Runtime
      azure_rm_webapp:
        resource_group: "{{ resource_group }}"
        name: "{{ webapp_name }}"
        app_settings:
          connstring: "{{ connection_string }}"
          WEBSITE_RUN_FROM_PACKAGE: "1"
        plan:
          resource_group: "{{ resource_group }}"
          name: "{{ asp_name }}"
          is_linux: true
          sku: B1
          number_of_workers: 1
        frameworks:
          - name: "php"
            version: "7.3"

    - name: Fetch app service facts
      azure_rm_webapp_info:
        resource_group: "{{ resource_group }}"
        name: "{{ webapp_name }}"
        return_publish_profile: true
      register: find_output

    - name: Deploy to app service using ftp
      local_action:
        module: ftp
        #ftps://waws-prod-blu-175.ftp.azurewebsites.windows.net/site/wwwroot
        #waws-prod-blu-175.ftp.azurewebsites.windows.net
        host: "{{ find_output.webapps[0].ftp_publish_url.split('\/')[2] }}"
        user: "{{ webapp_name }}"
        password: "{{ find_output.webapps[0].publishing_password }}"
        src: /tmp/deploy/webApp.zip
        dest: 'data/SitePackages/'
        direction: push

    - name: Configure app service
      local_action:
        module: ftp
        host: "{{ find_output.webapps[0].ftp_publish_url.split('\/')[2] }}"
        user: "{{ webapp_name }}"
        password: "{{ find_output.webapps[0].publishing_password }}"
        src: /tmp/deploy/packagename.txt
        dest: 'data/SitePackages/'
        direction: push

    - name: Create MySQL Server
      azure_rm_mysqlserver:
        resource_group: "{{ resource_group }}"
        name: "{{ mysqlserver_name }}"
        sku:
          name: B_Gen5_1
          tier: Basic
        location: "{{ location }}"
        version: "5.7"
        enforce_ssl: false
        admin_username: "{{ admin_username }}"
        admin_password: "{{ admin_password }}"
        storage_mb: 5120

    - name: Open firewall to access MySQL Server from outside
      azure_rm_resource:
        api_version: '2017-12-01'
        resource_group: "{{ resource_group }}"
        provider: dbformysql
        resource_type: servers
        resource_name: "{{ mysqlserver_name }}"
        subresource:
          - type: firewallrules
            name: externalaccess
        body:
          properties:
            startIpAddress: "0.0.0.0"
            endIpAddress: "0.0.0.0"
    - name: Create instance of MySQL Database
      azure_rm_mysqldatabase:
        resource_group: "{{ resource_group }}"
        server_name: "{{ mysqlserver_name }}"
        name: "{{ mysqldb_name }}"

    - name: Create users table from file
      shell: >
        mysql --user={{ admin_username }}@{{ mysqlserver_name }} --password={{ admin_password }} {{ mysqldb_name }}
        --host={{ mysqlserver_name }}.mysql.database.azure.com < /tmp/deploy/users.sql
      register: stuff
      check_mode: no
      changed_when: False
      args:
        warn: false
